"""
Generated by tools/generate_pytest_from_properties.py.

These optional property tests use Hypothesis to vary source dataclass fields
for the same conservative transform relations as the generated example tests.
"""

from __future__ import annotations

import abc
import importlib

import pytest

pytest.importorskip("hypothesis")
from hypothesis import given, settings, strategies as st


CASES = [

]


def _load_class(module_name, class_name):
    try:
        module = importlib.import_module(module_name)
    except ModuleNotFoundError as exc:
        pytest.skip(f"Cannot import {module_name}: {exc}")
    return getattr(module, class_name)


def _dummy_method(*args, **kwargs):
    return None


def _instance_for(cls):
    try:
        return cls()
    except TypeError:
        attrs = {}
        abstract_names = getattr(cls, "__abstractmethods__", set())
        for name in abstract_names:
            descriptor = getattr(cls, name, None)
            if isinstance(descriptor, property):
                attrs[name] = property(lambda self, _name=name: f"generated-{_name}")
            else:
                attrs[name] = _dummy_method

        harness = abc.ABCMeta(f"Generated{cls.__name__}Harness", (cls,), attrs)
        return harness()


def _assert_observed(actual, expected):
    if actual == expected:
        return

    if expected is None:
        assert actual is None
        return

    expected_text = str(expected)

    if isinstance(actual, str):
        assert expected_text in actual
        return

    if isinstance(actual, list):
        normalized = expected_text.lower().replace(" ", "")
        location_prefix = expected_text.split(",", 1)[0].capitalize()
        actual_texts = [str(item) for item in actual]
        actual_normalized = [item.lower().replace(" ", "") for item in actual_texts]
        assert (
            expected_text in actual_texts
            or normalized in actual_normalized
            or location_prefix in actual_texts
        )
        return

    assert actual == expected


def _safe_text(min_size=1, max_size=24):
    alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 -_"
    return st.text(alphabet=alphabet, min_size=min_size, max_size=max_size)


def _strategy_for_case(case):
    name = case["source_field"].lower()
    type_repr = case["source_type"].lower()

    if case["assertion"] == "equals" and case["target_kind"] == "optional":
        if "url" in name or "link" in name:
            return st.one_of(
                st.none(),
                st.just(""),
                _safe_text(max_size=20).map(lambda value: f"https://example.com/{value}"),
            )
        return st.one_of(st.none(), st.just(""), _safe_text(max_size=32))

    if "list" in type_repr:
        return st.lists(_safe_text(max_size=12), min_size=1, max_size=4)
    if "bool" in type_repr:
        return st.booleans()
    if "int" in type_repr:
        return st.integers(min_value=-100, max_value=100)
    if name == "location":
        return _safe_text(max_size=16).map(lambda value: f"Generated {value}, MA")
    if "url" in name or "link" in name:
        return _safe_text(max_size=20).map(lambda value: f"https://example.com/{value}")
    return _safe_text(max_size=32)


def _run_case(case, source_value):
    source_cls = _load_class(case["source_module"], case["source_class"])
    owner_cls = _load_class(case["class_module"], case["class_name"])

    input_kwargs = dict(case["input_kwargs"])
    input_kwargs[case["source_field"]] = source_value
    source = source_cls(**input_kwargs)

    owner = _instance_for(owner_cls)
    result = getattr(owner, case["method_name"])(source)
    actual = getattr(result, case["target_arg"])

    if case["assertion"] == "equals":
        assert actual == source_value
    else:
        _assert_observed(actual, source_value)


@pytest.mark.parametrize("case", CASES, ids=[case["id"] for case in CASES])
def test_generated_dataclass_transform_property_hypothesis(case):
    @settings(max_examples=25, deadline=None)
    @given(source_value=_strategy_for_case(case))
    def property_check(source_value):
        _run_case(case, source_value)

    property_check()
