"""
Generated by tools/generate_pytest_from_properties.py.

These tests exercise generic dataclass conversion APIs such as from_dict,
structure, to_dict, and unstructure. They define local dataclasses so the target
library can be tested without relying on project-specific domain models.
"""

from __future__ import annotations

import dataclasses
import importlib

import pytest


CONVERSION_CASES = [
    {
        'id': 'conversion-dict_to_dataclass-core-from_dict',
        'module_name': 'dacite.core',
        'qualified_name': 'from_dict',
        'function_name': 'from_dict',
        'owner_class': '',
        'profile': 'dict_to_dataclass',
    }
]


@dataclasses.dataclass
class GeneratedNested:
    label: str
    count: int = 3


@dataclasses.dataclass
class GeneratedItem:
    name: str
    enabled: bool
    tags: list[str]
    nested: GeneratedNested


def _load_callable(case):
    try:
        module = importlib.import_module(case["module_name"])
    except ModuleNotFoundError as exc:
        pytest.skip(f"Cannot import {case['module_name']}: {exc}")

    if case["owner_class"]:
        owner_cls = getattr(module, case["owner_class"])
        try:
            owner = owner_cls()
        except Exception as exc:
            pytest.skip(f"Cannot instantiate {case['owner_class']}: {exc}")
        return getattr(owner, case["function_name"])

    target = module
    for part in case["qualified_name"].split("."):
        target = getattr(target, part)
    return target


def _call_first_success(func, attempts):
    errors = []
    for args, kwargs in attempts:
        try:
            return func(*args, **kwargs)
        except TypeError as exc:
            errors.append(str(exc))
    pytest.skip("No supported conversion signature matched: " + " | ".join(errors[:3]))


def _input_data():
    return {
        "name": "generated-name",
        "enabled": True,
        "tags": ["alpha", "beta"],
        "nested": {"label": "child", "count": 5},
    }


@pytest.mark.parametrize("case", CONVERSION_CASES, ids=[case["id"] for case in CONVERSION_CASES])
def test_generated_dataclass_conversion_profile(case):
    func = _load_callable(case)

    if case["profile"] == "dict_to_dataclass":
        data = _input_data()
        result = _call_first_success(
            func,
            [
                ((), {"data_class": GeneratedItem, "data": data}),
                ((GeneratedItem, data), {}),
                ((data, GeneratedItem), {}),
                ((), {"cl": GeneratedItem, "obj": data}),
            ],
        )
        assert dataclasses.is_dataclass(result)
        assert result.name == data["name"]
        assert result.enabled is True
        assert result.tags == data["tags"]
        assert dataclasses.is_dataclass(result.nested)
        assert result.nested.label == data["nested"]["label"]
        return

    item = GeneratedItem(
        name="generated-name",
        enabled=True,
        tags=["alpha", "beta"],
        nested=GeneratedNested(label="child", count=5),
    )
    result = _call_first_success(
        func,
        [
            ((item,), {}),
            ((), {"obj": item}),
        ],
    )
    assert isinstance(result, dict)
    assert result["name"] == item.name
    assert result["enabled"] is True
    assert result["tags"] == item.tags
    assert result["nested"]["label"] == item.nested.label
