"""
Generated by tools/generate_pytest_from_properties.py.

These tests exercise runtime dataclass schema and constructor behavior. They are
intended to provide portable executable oracles for dataclass-heavy projects even
when no project-specific dataclass transform oracle is available.
"""

from __future__ import annotations

import dataclasses
import importlib
import types
import typing

import pytest


SCHEMA_CASES = [
    {
        'id': 'schema-config-Config',
        'module_name': 'dacite.config',
        'class_name': 'Config',
        'is_frozen': False,
        'options': {'eq': 'true', 'frozen': 'false', 'init': 'true', 'kw_only': 'false', 'match_args': 'true', 'order': 'false', 'repr': 'true', 'slots': 'false', 'unsafe_hash': 'false', 'weakref_slot': 'false'},
        'fields': [{'name': 'type_hooks', 'type_repr': 'Dict[Type, Callable[[Any], Any]]', 'is_optional': False, 'has_default': True, 'default_kind': 'factory'}, {'name': 'cast', 'type_repr': 'List[Type]', 'is_optional': False, 'has_default': True, 'default_kind': 'factory'}, {'name': 'forward_references', 'type_repr': 'Optional[Dict[str, Any]]', 'is_optional': True, 'has_default': True, 'default_kind': 'literal'}, {'name': 'check_types', 'type_repr': 'bool', 'is_optional': False, 'has_default': True, 'default_kind': 'literal'}, {'name': 'strict', 'type_repr': 'bool', 'is_optional': False, 'has_default': True, 'default_kind': 'literal'}, {'name': 'strict_unions_match', 'type_repr': 'bool', 'is_optional': False, 'has_default': True, 'default_kind': 'literal'}, {'name': 'convert_key', 'type_repr': 'Callable[[str], str]', 'is_optional': False, 'has_default': True, 'default_kind': 'factory'}],
    }
]


CONSTRUCTOR_CASES = [
    {
        'id': 'constructor-config-Config',
        'module_name': 'dacite.config',
        'class_name': 'Config',
        'required_kwargs': {},
        'required_fields': [],
        'defaulted_fields': ['type_hooks', 'cast', 'forward_references', 'check_types', 'strict', 'strict_unions_match', 'convert_key'],
        'factory_fields': ['type_hooks', 'cast', 'convert_key'],
    }
]


def _load_class(module_name, class_name):
    try:
        module = importlib.import_module(module_name)
    except ModuleNotFoundError as exc:
        pytest.skip(f"Cannot import {module_name}: {exc}")
    return getattr(module, class_name)


def _dataclass_param(cls, name):
    params = getattr(cls, "__dataclass_params__", None)
    if params is None or not hasattr(params, name):
        return None
    return getattr(params, name)


def _sample_for_annotation(annotation, field_name, depth=0):
    if depth > 2:
        return None
    if isinstance(annotation, str):
        lowered_annotation = annotation.lower()
        if "str" in lowered_annotation:
            return f"generated_{field_name}"
        if "bool" in lowered_annotation:
            return True
        if "float" in lowered_annotation:
            return 3.5
        if "int" in lowered_annotation:
            return 7
        if "list" in lowered_annotation:
            return [f"generated_{field_name}_item"]
        if "dict" in lowered_annotation:
            return {"generated_key": f"generated_{field_name}"}
        return f"generated_{field_name}"

    origin = typing.get_origin(annotation)
    args = typing.get_args(annotation)
    if origin is types.UnionType or origin is typing.Union:
        non_none_args = [arg for arg in args if arg is not type(None)]
        return _sample_for_annotation(non_none_args[0], field_name, depth + 1) if non_none_args else None
    if origin in {list, tuple, set, frozenset}:
        item_type = args[0] if args else str
        item = _sample_for_annotation(item_type, f"{field_name}_item", depth + 1)
        if origin is tuple:
            return (item,)
        if origin is set:
            return {item}
        if origin is frozenset:
            return frozenset({item})
        return [item]
    if origin is dict:
        value_type = args[1] if len(args) > 1 else str
        return {"generated_key": _sample_for_annotation(value_type, field_name, depth + 1)}
    if dataclasses.is_dataclass(annotation):
        return _instance_from_runtime_fields(annotation, depth + 1)
    if annotation is str:
        return f"generated_{field_name}"
    if annotation is bool:
        return True
    if annotation is int:
        return 7
    if annotation is float:
        return 3.5
    if annotation is bytes:
        return b"generated"
    return f"generated_{field_name}"


def _required_runtime_fields(cls):
    return [
        field
        for field in dataclasses.fields(cls)
        if field.init
        and field.default is dataclasses.MISSING
        and field.default_factory is dataclasses.MISSING
    ]


def _instance_from_runtime_fields(cls, depth=0):
    kwargs = {
        field.name: _sample_for_annotation(field.type, field.name, depth)
        for field in _required_runtime_fields(cls)
    }
    return cls(**kwargs)


@pytest.mark.parametrize("case", SCHEMA_CASES, ids=[case["id"] for case in SCHEMA_CASES])
def test_generated_dataclass_runtime_schema(case):
    cls = _load_class(case["module_name"], case["class_name"])

    if not dataclasses.is_dataclass(cls):
        pytest.skip(
            f"{cls.__module__}.{cls.__qualname__} is not a runtime dataclass "
            "in this dependency configuration"
        )

    assert _dataclass_param(cls, "frozen") == case["is_frozen"]

    runtime_fields = {field.name: field for field in dataclasses.fields(cls)}
    for expected in case["fields"]:
        name = expected["name"]
        assert name in runtime_fields
        runtime_field = runtime_fields[name]
        has_runtime_default = (
            runtime_field.default is not dataclasses.MISSING
            or runtime_field.default_factory is not dataclasses.MISSING
        )
        assert has_runtime_default == expected["has_default"]
        if expected["default_kind"] == "factory":
            assert runtime_field.default_factory is not dataclasses.MISSING

    for option_name in ("repr", "eq", "order", "unsafe_hash"):
        expected_value = case["options"].get(option_name)
        actual_value = _dataclass_param(cls, option_name)
        if expected_value is not None and actual_value is not None:
            assert actual_value == (expected_value == "true")

    if case["options"].get("slots") == "true":
        assert hasattr(cls, "__slots__")
    if case["options"].get("match_args") == "false":
        assert not hasattr(cls, "__match_args__")


@pytest.mark.parametrize("case", CONSTRUCTOR_CASES, ids=[case["id"] for case in CONSTRUCTOR_CASES])
def test_generated_dataclass_constructor_defaults(case):
    cls = _load_class(case["module_name"], case["class_name"])

    if not dataclasses.is_dataclass(cls):
        pytest.skip(
            f"{cls.__module__}.{cls.__qualname__} is not a runtime dataclass "
            "in this dependency configuration"
        )

    try:
        first = _instance_from_runtime_fields(cls)
        second = _instance_from_runtime_fields(cls)
    except Exception as exc:
        pytest.skip(f"Generated constructor fixture is not valid for {cls.__name__}: {exc}")

    generated_required_fields = [field.name for field in _required_runtime_fields(cls)]
    for field_name in generated_required_fields:
        assert hasattr(first, field_name)

    for field_name in case["defaulted_fields"]:
        assert hasattr(first, field_name)

    for field_name in case["factory_fields"]:
        first_value = getattr(first, field_name)
        second_value = getattr(second, field_name)
        if isinstance(first_value, (list, dict, set)):
            assert first_value is not second_value

    if generated_required_fields:
        missing_field = generated_required_fields[0]
        kwargs = {
            field.name: _sample_for_annotation(field.type, field.name)
            for field in _required_runtime_fields(cls)
            if field.name != missing_field
        }
        with pytest.raises(TypeError):
            cls(**kwargs)
