"""
Generated by tools/generate_pytest_from_properties.py.

These tests are intentionally portable: keep them outside the analyzed project
and run them with PYTHONPATH pointing at the target checkout, for example:

    PYTHONPATH=/path/to/CutePetsBoston pytest generated_tests/<project>
"""

from __future__ import annotations

import abc
import importlib

import pytest


CASES = [
    {
        'id': 'SocialPoster.format_post-AdoptablePet-breed-Post-text-value',
        'class_module': 'abstractions',
        'class_name': 'SocialPoster',
        'method_name': 'format_post',
        'source_module': 'abstractions',
        'source_class': 'AdoptablePet',
        'source_field': 'breed',
        'target_arg': 'text',
        'assertion': 'observes',
        'input_kwargs': {'name': 'generatedname', 'species': 'generatedspecies', 'breed': 'generatedbreed', 'location': 'generatedcity, MA', 'description': 'generatedtext', 'adoption_url': None, 'image_url': None, 'age_string': None, 'sex': None, 'size_group': None, 'pet_id': None},
    },
    {
        'id': 'SocialPoster.format_post-AdoptablePet-breed-Post-tags-value',
        'class_module': 'abstractions',
        'class_name': 'SocialPoster',
        'method_name': 'format_post',
        'source_module': 'abstractions',
        'source_class': 'AdoptablePet',
        'source_field': 'breed',
        'target_arg': 'tags',
        'assertion': 'observes',
        'input_kwargs': {'name': 'generatedname', 'species': 'generatedspecies', 'breed': 'generatedbreed', 'location': 'generatedcity, MA', 'description': 'generatedtext', 'adoption_url': None, 'image_url': None, 'age_string': None, 'sex': None, 'size_group': None, 'pet_id': None},
    },
    {
        'id': 'SocialPoster.format_post-AdoptablePet-breed-Post-alt_text-value',
        'class_module': 'abstractions',
        'class_name': 'SocialPoster',
        'method_name': 'format_post',
        'source_module': 'abstractions',
        'source_class': 'AdoptablePet',
        'source_field': 'breed',
        'target_arg': 'alt_text',
        'assertion': 'observes',
        'input_kwargs': {'name': 'generatedname', 'species': 'generatedspecies', 'breed': 'generatedbreed', 'location': 'generatedcity, MA', 'description': 'generatedtext', 'adoption_url': None, 'image_url': None, 'age_string': None, 'sex': None, 'size_group': None, 'pet_id': None},
    },
    {
        'id': 'SocialPoster.format_post-AdoptablePet-location-Post-text-value',
        'class_module': 'abstractions',
        'class_name': 'SocialPoster',
        'method_name': 'format_post',
        'source_module': 'abstractions',
        'source_class': 'AdoptablePet',
        'source_field': 'location',
        'target_arg': 'text',
        'assertion': 'observes',
        'input_kwargs': {'name': 'generatedname', 'species': 'generatedspecies', 'breed': 'generatedbreed', 'location': 'generatedcity, MA', 'description': 'generatedtext', 'adoption_url': None, 'image_url': None, 'age_string': None, 'sex': None, 'size_group': None, 'pet_id': None},
    },
    {
        'id': 'SocialPoster.format_post-AdoptablePet-location-Post-tags-value',
        'class_module': 'abstractions',
        'class_name': 'SocialPoster',
        'method_name': 'format_post',
        'source_module': 'abstractions',
        'source_class': 'AdoptablePet',
        'source_field': 'location',
        'target_arg': 'tags',
        'assertion': 'observes',
        'input_kwargs': {'name': 'generatedname', 'species': 'generatedspecies', 'breed': 'generatedbreed', 'location': 'generatedcity, MA', 'description': 'generatedtext', 'adoption_url': None, 'image_url': None, 'age_string': None, 'sex': None, 'size_group': None, 'pet_id': None},
    },
    {
        'id': 'SocialPoster.format_post-AdoptablePet-name-Post-text-value',
        'class_module': 'abstractions',
        'class_name': 'SocialPoster',
        'method_name': 'format_post',
        'source_module': 'abstractions',
        'source_class': 'AdoptablePet',
        'source_field': 'name',
        'target_arg': 'text',
        'assertion': 'observes',
        'input_kwargs': {'name': 'generatedname', 'species': 'generatedspecies', 'breed': 'generatedbreed', 'location': 'generatedcity, MA', 'description': 'generatedtext', 'adoption_url': None, 'image_url': None, 'age_string': None, 'sex': None, 'size_group': None, 'pet_id': None},
    },
    {
        'id': 'SocialPoster.format_post-AdoptablePet-name-Post-alt_text-value',
        'class_module': 'abstractions',
        'class_name': 'SocialPoster',
        'method_name': 'format_post',
        'source_module': 'abstractions',
        'source_class': 'AdoptablePet',
        'source_field': 'name',
        'target_arg': 'alt_text',
        'assertion': 'observes',
        'input_kwargs': {'name': 'generatedname', 'species': 'generatedspecies', 'breed': 'generatedbreed', 'location': 'generatedcity, MA', 'description': 'generatedtext', 'adoption_url': None, 'image_url': None, 'age_string': None, 'sex': None, 'size_group': None, 'pet_id': None},
    },
    {
        'id': 'SocialPoster.format_post-AdoptablePet-species-Post-text-value',
        'class_module': 'abstractions',
        'class_name': 'SocialPoster',
        'method_name': 'format_post',
        'source_module': 'abstractions',
        'source_class': 'AdoptablePet',
        'source_field': 'species',
        'target_arg': 'text',
        'assertion': 'observes',
        'input_kwargs': {'name': 'generatedname', 'species': 'generatedspecies', 'breed': 'generatedbreed', 'location': 'generatedcity, MA', 'description': 'generatedtext', 'adoption_url': None, 'image_url': None, 'age_string': None, 'sex': None, 'size_group': None, 'pet_id': None},
    },
    {
        'id': 'SocialPoster.format_post-AdoptablePet-species-Post-tags-value',
        'class_module': 'abstractions',
        'class_name': 'SocialPoster',
        'method_name': 'format_post',
        'source_module': 'abstractions',
        'source_class': 'AdoptablePet',
        'source_field': 'species',
        'target_arg': 'tags',
        'assertion': 'observes',
        'input_kwargs': {'name': 'generatedname', 'species': 'generatedspecies', 'breed': 'generatedbreed', 'location': 'generatedcity, MA', 'description': 'generatedtext', 'adoption_url': None, 'image_url': None, 'age_string': None, 'sex': None, 'size_group': None, 'pet_id': None},
    },
    {
        'id': 'SocialPoster.format_post-AdoptablePet-species-Post-alt_text-value',
        'class_module': 'abstractions',
        'class_name': 'SocialPoster',
        'method_name': 'format_post',
        'source_module': 'abstractions',
        'source_class': 'AdoptablePet',
        'source_field': 'species',
        'target_arg': 'alt_text',
        'assertion': 'observes',
        'input_kwargs': {'name': 'generatedname', 'species': 'generatedspecies', 'breed': 'generatedbreed', 'location': 'generatedcity, MA', 'description': 'generatedtext', 'adoption_url': None, 'image_url': None, 'age_string': None, 'sex': None, 'size_group': None, 'pet_id': None},
    },
    {
        'id': 'PosterMastodon.format_post-AdoptablePet-breed-Post-text-value',
        'class_module': 'social_posters.mastodon',
        'class_name': 'PosterMastodon',
        'method_name': 'format_post',
        'source_module': 'abstractions',
        'source_class': 'AdoptablePet',
        'source_field': 'breed',
        'target_arg': 'text',
        'assertion': 'observes',
        'input_kwargs': {'name': 'generatedname', 'species': 'generatedspecies', 'breed': 'generatedbreed', 'location': 'generatedcity, MA', 'description': 'generatedtext', 'adoption_url': None, 'image_url': None, 'age_string': None, 'sex': None, 'size_group': None, 'pet_id': None},
    },
    {
        'id': 'PosterMastodon.format_post-AdoptablePet-breed-Post-tags-value',
        'class_module': 'social_posters.mastodon',
        'class_name': 'PosterMastodon',
        'method_name': 'format_post',
        'source_module': 'abstractions',
        'source_class': 'AdoptablePet',
        'source_field': 'breed',
        'target_arg': 'tags',
        'assertion': 'observes',
        'input_kwargs': {'name': 'generatedname', 'species': 'generatedspecies', 'breed': 'generatedbreed', 'location': 'generatedcity, MA', 'description': 'generatedtext', 'adoption_url': None, 'image_url': None, 'age_string': None, 'sex': None, 'size_group': None, 'pet_id': None},
    },
    {
        'id': 'PosterMastodon.format_post-AdoptablePet-breed-Post-alt_text-value',
        'class_module': 'social_posters.mastodon',
        'class_name': 'PosterMastodon',
        'method_name': 'format_post',
        'source_module': 'abstractions',
        'source_class': 'AdoptablePet',
        'source_field': 'breed',
        'target_arg': 'alt_text',
        'assertion': 'observes',
        'input_kwargs': {'name': 'generatedname', 'species': 'generatedspecies', 'breed': 'generatedbreed', 'location': 'generatedcity, MA', 'description': 'generatedtext', 'adoption_url': None, 'image_url': None, 'age_string': None, 'sex': None, 'size_group': None, 'pet_id': None},
    },
    {
        'id': 'PosterMastodon.format_post-AdoptablePet-location-Post-text-value',
        'class_module': 'social_posters.mastodon',
        'class_name': 'PosterMastodon',
        'method_name': 'format_post',
        'source_module': 'abstractions',
        'source_class': 'AdoptablePet',
        'source_field': 'location',
        'target_arg': 'text',
        'assertion': 'observes',
        'input_kwargs': {'name': 'generatedname', 'species': 'generatedspecies', 'breed': 'generatedbreed', 'location': 'generatedcity, MA', 'description': 'generatedtext', 'adoption_url': None, 'image_url': None, 'age_string': None, 'sex': None, 'size_group': None, 'pet_id': None},
    },
    {
        'id': 'PosterMastodon.format_post-AdoptablePet-location-Post-tags-value',
        'class_module': 'social_posters.mastodon',
        'class_name': 'PosterMastodon',
        'method_name': 'format_post',
        'source_module': 'abstractions',
        'source_class': 'AdoptablePet',
        'source_field': 'location',
        'target_arg': 'tags',
        'assertion': 'observes',
        'input_kwargs': {'name': 'generatedname', 'species': 'generatedspecies', 'breed': 'generatedbreed', 'location': 'generatedcity, MA', 'description': 'generatedtext', 'adoption_url': None, 'image_url': None, 'age_string': None, 'sex': None, 'size_group': None, 'pet_id': None},
    },
    {
        'id': 'PosterMastodon.format_post-AdoptablePet-name-Post-text-value',
        'class_module': 'social_posters.mastodon',
        'class_name': 'PosterMastodon',
        'method_name': 'format_post',
        'source_module': 'abstractions',
        'source_class': 'AdoptablePet',
        'source_field': 'name',
        'target_arg': 'text',
        'assertion': 'observes',
        'input_kwargs': {'name': 'generatedname', 'species': 'generatedspecies', 'breed': 'generatedbreed', 'location': 'generatedcity, MA', 'description': 'generatedtext', 'adoption_url': None, 'image_url': None, 'age_string': None, 'sex': None, 'size_group': None, 'pet_id': None},
    },
    {
        'id': 'PosterMastodon.format_post-AdoptablePet-name-Post-alt_text-value',
        'class_module': 'social_posters.mastodon',
        'class_name': 'PosterMastodon',
        'method_name': 'format_post',
        'source_module': 'abstractions',
        'source_class': 'AdoptablePet',
        'source_field': 'name',
        'target_arg': 'alt_text',
        'assertion': 'observes',
        'input_kwargs': {'name': 'generatedname', 'species': 'generatedspecies', 'breed': 'generatedbreed', 'location': 'generatedcity, MA', 'description': 'generatedtext', 'adoption_url': None, 'image_url': None, 'age_string': None, 'sex': None, 'size_group': None, 'pet_id': None},
    },
    {
        'id': 'PosterMastodon.format_post-AdoptablePet-species-Post-text-value',
        'class_module': 'social_posters.mastodon',
        'class_name': 'PosterMastodon',
        'method_name': 'format_post',
        'source_module': 'abstractions',
        'source_class': 'AdoptablePet',
        'source_field': 'species',
        'target_arg': 'text',
        'assertion': 'observes',
        'input_kwargs': {'name': 'generatedname', 'species': 'generatedspecies', 'breed': 'generatedbreed', 'location': 'generatedcity, MA', 'description': 'generatedtext', 'adoption_url': None, 'image_url': None, 'age_string': None, 'sex': None, 'size_group': None, 'pet_id': None},
    },
    {
        'id': 'PosterMastodon.format_post-AdoptablePet-species-Post-tags-value',
        'class_module': 'social_posters.mastodon',
        'class_name': 'PosterMastodon',
        'method_name': 'format_post',
        'source_module': 'abstractions',
        'source_class': 'AdoptablePet',
        'source_field': 'species',
        'target_arg': 'tags',
        'assertion': 'observes',
        'input_kwargs': {'name': 'generatedname', 'species': 'generatedspecies', 'breed': 'generatedbreed', 'location': 'generatedcity, MA', 'description': 'generatedtext', 'adoption_url': None, 'image_url': None, 'age_string': None, 'sex': None, 'size_group': None, 'pet_id': None},
    },
    {
        'id': 'PosterMastodon.format_post-AdoptablePet-species-Post-alt_text-value',
        'class_module': 'social_posters.mastodon',
        'class_name': 'PosterMastodon',
        'method_name': 'format_post',
        'source_module': 'abstractions',
        'source_class': 'AdoptablePet',
        'source_field': 'species',
        'target_arg': 'alt_text',
        'assertion': 'observes',
        'input_kwargs': {'name': 'generatedname', 'species': 'generatedspecies', 'breed': 'generatedbreed', 'location': 'generatedcity, MA', 'description': 'generatedtext', 'adoption_url': None, 'image_url': None, 'age_string': None, 'sex': None, 'size_group': None, 'pet_id': None},
    },
    {
        'id': 'SocialPoster.format_post-AdoptablePet-adoption_url-Post-link-none',
        'class_module': 'abstractions',
        'class_name': 'SocialPoster',
        'method_name': 'format_post',
        'source_module': 'abstractions',
        'source_class': 'AdoptablePet',
        'source_field': 'adoption_url',
        'target_arg': 'link',
        'assertion': 'equals',
        'input_kwargs': {'name': 'generatedname', 'species': 'generatedspecies', 'breed': 'generatedbreed', 'location': 'generatedcity, MA', 'description': 'generatedtext', 'adoption_url': None, 'image_url': None, 'age_string': None, 'sex': None, 'size_group': None, 'pet_id': None},
    },
    {
        'id': 'SocialPoster.format_post-AdoptablePet-adoption_url-Post-link-empty',
        'class_module': 'abstractions',
        'class_name': 'SocialPoster',
        'method_name': 'format_post',
        'source_module': 'abstractions',
        'source_class': 'AdoptablePet',
        'source_field': 'adoption_url',
        'target_arg': 'link',
        'assertion': 'equals',
        'input_kwargs': {'name': 'generatedname', 'species': 'generatedspecies', 'breed': 'generatedbreed', 'location': 'generatedcity, MA', 'description': 'generatedtext', 'adoption_url': '', 'image_url': None, 'age_string': None, 'sex': None, 'size_group': None, 'pet_id': None},
    },
    {
        'id': 'SocialPoster.format_post-AdoptablePet-adoption_url-Post-link-value',
        'class_module': 'abstractions',
        'class_name': 'SocialPoster',
        'method_name': 'format_post',
        'source_module': 'abstractions',
        'source_class': 'AdoptablePet',
        'source_field': 'adoption_url',
        'target_arg': 'link',
        'assertion': 'equals',
        'input_kwargs': {'name': 'generatedname', 'species': 'generatedspecies', 'breed': 'generatedbreed', 'location': 'generatedcity, MA', 'description': 'generatedtext', 'adoption_url': 'https://example.com/generated-value', 'image_url': None, 'age_string': None, 'sex': None, 'size_group': None, 'pet_id': None},
    },
    {
        'id': 'SocialPoster.format_post-AdoptablePet-image_url-Post-image_url-none',
        'class_module': 'abstractions',
        'class_name': 'SocialPoster',
        'method_name': 'format_post',
        'source_module': 'abstractions',
        'source_class': 'AdoptablePet',
        'source_field': 'image_url',
        'target_arg': 'image_url',
        'assertion': 'equals',
        'input_kwargs': {'name': 'generatedname', 'species': 'generatedspecies', 'breed': 'generatedbreed', 'location': 'generatedcity, MA', 'description': 'generatedtext', 'adoption_url': None, 'image_url': None, 'age_string': None, 'sex': None, 'size_group': None, 'pet_id': None},
    },
    {
        'id': 'SocialPoster.format_post-AdoptablePet-image_url-Post-image_url-empty',
        'class_module': 'abstractions',
        'class_name': 'SocialPoster',
        'method_name': 'format_post',
        'source_module': 'abstractions',
        'source_class': 'AdoptablePet',
        'source_field': 'image_url',
        'target_arg': 'image_url',
        'assertion': 'equals',
        'input_kwargs': {'name': 'generatedname', 'species': 'generatedspecies', 'breed': 'generatedbreed', 'location': 'generatedcity, MA', 'description': 'generatedtext', 'adoption_url': None, 'image_url': '', 'age_string': None, 'sex': None, 'size_group': None, 'pet_id': None},
    },
    {
        'id': 'SocialPoster.format_post-AdoptablePet-image_url-Post-image_url-value',
        'class_module': 'abstractions',
        'class_name': 'SocialPoster',
        'method_name': 'format_post',
        'source_module': 'abstractions',
        'source_class': 'AdoptablePet',
        'source_field': 'image_url',
        'target_arg': 'image_url',
        'assertion': 'equals',
        'input_kwargs': {'name': 'generatedname', 'species': 'generatedspecies', 'breed': 'generatedbreed', 'location': 'generatedcity, MA', 'description': 'generatedtext', 'adoption_url': None, 'image_url': 'https://example.com/generated-value', 'age_string': None, 'sex': None, 'size_group': None, 'pet_id': None},
    },
    {
        'id': 'PosterMastodon.format_post-AdoptablePet-adoption_url-Post-link-none',
        'class_module': 'social_posters.mastodon',
        'class_name': 'PosterMastodon',
        'method_name': 'format_post',
        'source_module': 'abstractions',
        'source_class': 'AdoptablePet',
        'source_field': 'adoption_url',
        'target_arg': 'link',
        'assertion': 'equals',
        'input_kwargs': {'name': 'generatedname', 'species': 'generatedspecies', 'breed': 'generatedbreed', 'location': 'generatedcity, MA', 'description': 'generatedtext', 'adoption_url': None, 'image_url': None, 'age_string': None, 'sex': None, 'size_group': None, 'pet_id': None},
    },
    {
        'id': 'PosterMastodon.format_post-AdoptablePet-adoption_url-Post-link-empty',
        'class_module': 'social_posters.mastodon',
        'class_name': 'PosterMastodon',
        'method_name': 'format_post',
        'source_module': 'abstractions',
        'source_class': 'AdoptablePet',
        'source_field': 'adoption_url',
        'target_arg': 'link',
        'assertion': 'equals',
        'input_kwargs': {'name': 'generatedname', 'species': 'generatedspecies', 'breed': 'generatedbreed', 'location': 'generatedcity, MA', 'description': 'generatedtext', 'adoption_url': '', 'image_url': None, 'age_string': None, 'sex': None, 'size_group': None, 'pet_id': None},
    },
    {
        'id': 'PosterMastodon.format_post-AdoptablePet-adoption_url-Post-link-value',
        'class_module': 'social_posters.mastodon',
        'class_name': 'PosterMastodon',
        'method_name': 'format_post',
        'source_module': 'abstractions',
        'source_class': 'AdoptablePet',
        'source_field': 'adoption_url',
        'target_arg': 'link',
        'assertion': 'equals',
        'input_kwargs': {'name': 'generatedname', 'species': 'generatedspecies', 'breed': 'generatedbreed', 'location': 'generatedcity, MA', 'description': 'generatedtext', 'adoption_url': 'https://example.com/generated-value', 'image_url': None, 'age_string': None, 'sex': None, 'size_group': None, 'pet_id': None},
    },
    {
        'id': 'PosterMastodon.format_post-AdoptablePet-image_url-Post-image_url-none',
        'class_module': 'social_posters.mastodon',
        'class_name': 'PosterMastodon',
        'method_name': 'format_post',
        'source_module': 'abstractions',
        'source_class': 'AdoptablePet',
        'source_field': 'image_url',
        'target_arg': 'image_url',
        'assertion': 'equals',
        'input_kwargs': {'name': 'generatedname', 'species': 'generatedspecies', 'breed': 'generatedbreed', 'location': 'generatedcity, MA', 'description': 'generatedtext', 'adoption_url': None, 'image_url': None, 'age_string': None, 'sex': None, 'size_group': None, 'pet_id': None},
    },
    {
        'id': 'PosterMastodon.format_post-AdoptablePet-image_url-Post-image_url-empty',
        'class_module': 'social_posters.mastodon',
        'class_name': 'PosterMastodon',
        'method_name': 'format_post',
        'source_module': 'abstractions',
        'source_class': 'AdoptablePet',
        'source_field': 'image_url',
        'target_arg': 'image_url',
        'assertion': 'equals',
        'input_kwargs': {'name': 'generatedname', 'species': 'generatedspecies', 'breed': 'generatedbreed', 'location': 'generatedcity, MA', 'description': 'generatedtext', 'adoption_url': None, 'image_url': '', 'age_string': None, 'sex': None, 'size_group': None, 'pet_id': None},
    },
    {
        'id': 'PosterMastodon.format_post-AdoptablePet-image_url-Post-image_url-value',
        'class_module': 'social_posters.mastodon',
        'class_name': 'PosterMastodon',
        'method_name': 'format_post',
        'source_module': 'abstractions',
        'source_class': 'AdoptablePet',
        'source_field': 'image_url',
        'target_arg': 'image_url',
        'assertion': 'equals',
        'input_kwargs': {'name': 'generatedname', 'species': 'generatedspecies', 'breed': 'generatedbreed', 'location': 'generatedcity, MA', 'description': 'generatedtext', 'adoption_url': None, 'image_url': 'https://example.com/generated-value', 'age_string': None, 'sex': None, 'size_group': None, 'pet_id': None},
    }
]


def _load_class(module_name, class_name):
    try:
        module = importlib.import_module(module_name)
    except ModuleNotFoundError as exc:
        pytest.skip(f"Cannot import {module_name}: {exc}")
    return getattr(module, class_name)


def _dummy_method(*args, **kwargs):
    return None


def _instance_for(cls):
    try:
        return cls()
    except TypeError:
        attrs = {}
        abstract_names = getattr(cls, "__abstractmethods__", set())
        for name in abstract_names:
            descriptor = getattr(cls, name, None)
            if isinstance(descriptor, property):
                attrs[name] = property(lambda self, _name=name: f"generated-{_name}")
            else:
                attrs[name] = _dummy_method

        harness = abc.ABCMeta(f"Generated{cls.__name__}Harness", (cls,), attrs)
        return harness()


def _assert_observed(actual, expected):
    if actual == expected:
        return

    if expected is None:
        assert actual is None
        return

    expected_text = str(expected)

    if isinstance(actual, str):
        assert expected_text in actual
        return

    if isinstance(actual, list):
        normalized = expected_text.lower().replace(" ", "")
        location_prefix = expected_text.split(",", 1)[0].capitalize()
        actual_texts = [str(item) for item in actual]
        actual_normalized = [item.lower().replace(" ", "") for item in actual_texts]
        assert (
            expected_text in actual_texts
            or normalized in actual_normalized
            or location_prefix in actual_texts
        )
        return

    assert actual == expected


@pytest.mark.parametrize("case", CASES, ids=[case["id"] for case in CASES])
def test_generated_dataclass_transform_property(case):
    source_cls = _load_class(case["source_module"], case["source_class"])
    owner_cls = _load_class(case["class_module"], case["class_name"])

    source = source_cls(**case["input_kwargs"])
    expected = case["input_kwargs"][case["source_field"]]

    owner = _instance_for(owner_cls)
    result = getattr(owner, case["method_name"])(source)
    actual = getattr(result, case["target_arg"])

    if case["assertion"] == "equals":
        assert actual == expected
    else:
        _assert_observed(actual, expected)
