"""
Generated by tools/generate_pytest_from_properties.py.

These are lower-confidence helper-boundary tests. They may call private helper
methods directly when the static boundary relation can be driven with a simple
string argument.
"""

from __future__ import annotations

import abc
import importlib

import pytest


HELPER_BOUNDARY_CASES = [
    {
        'id': 'SourceRescueGroups._clean_description-description-len-text--lower_exclusive-500-below',
        'module_name': 'adoption_sources.rescue_groups',
        'class_name': 'SourceRescueGroups',
        'method_name': '_clean_description',
        'param_name': 'description',
        'input_length': 499,
        'expected_max_length': 500,
        'relation_kind': 'lower_exclusive',
        'expression': 'len(text)',
    },
    {
        'id': 'SourceRescueGroups._clean_description-description-len-text--lower_exclusive-500-at',
        'module_name': 'adoption_sources.rescue_groups',
        'class_name': 'SourceRescueGroups',
        'method_name': '_clean_description',
        'param_name': 'description',
        'input_length': 500,
        'expected_max_length': 500,
        'relation_kind': 'lower_exclusive',
        'expression': 'len(text)',
    },
    {
        'id': 'SourceRescueGroups._clean_description-description-len-text--lower_exclusive-500-above',
        'module_name': 'adoption_sources.rescue_groups',
        'class_name': 'SourceRescueGroups',
        'method_name': '_clean_description',
        'param_name': 'description',
        'input_length': 501,
        'expected_max_length': 500,
        'relation_kind': 'lower_exclusive',
        'expression': 'len(text)',
    }
]


def _load_class(module_name, class_name):
    try:
        module = importlib.import_module(module_name)
    except ModuleNotFoundError as exc:
        pytest.skip(f"Cannot import {module_name}: {exc}")
    return getattr(module, class_name)


def _dummy_method(*args, **kwargs):
    return None


def _instance_for(cls):
    try:
        return cls()
    except TypeError:
        attrs = {}
        abstract_names = getattr(cls, "__abstractmethods__", set())
        for name in abstract_names:
            descriptor = getattr(cls, name, None)
            if isinstance(descriptor, property):
                attrs[name] = property(lambda self, _name=name: f"generated-{_name}")
            else:
                attrs[name] = _dummy_method

        harness = abc.ABCMeta(f"Generated{cls.__name__}Harness", (cls,), attrs)
        return harness()


@pytest.mark.parametrize("case", HELPER_BOUNDARY_CASES, ids=[case["id"] for case in HELPER_BOUNDARY_CASES])
def test_generated_helper_boundary(case):
    owner_cls = _load_class(case["module_name"], case["class_name"])
    owner = _instance_for(owner_cls)
    value = "x" * case["input_length"]

    result = getattr(owner, case["method_name"])(value)

    assert isinstance(result, str)
    assert len(result) <= case["expected_max_length"]
