"""
Generated by tools/generate_pytest_from_properties.py.

These tests exercise conservative common-AST semantic relations such as
iteration over dataclass collection fields.
"""

from __future__ import annotations

import abc
import importlib

import pytest


COMMON_AST_CASES = [

]


def _load_class(module_name, class_name):
    try:
        module = importlib.import_module(module_name)
    except ModuleNotFoundError as exc:
        pytest.skip(f"Cannot import {module_name}: {exc}")
    return getattr(module, class_name)


def _dummy_method(*args, **kwargs):
    return None


def _instance_for(cls):
    try:
        return cls()
    except TypeError:
        attrs = {}
        abstract_names = getattr(cls, "__abstractmethods__", set())
        for name in abstract_names:
            descriptor = getattr(cls, name, None)
            if isinstance(descriptor, property):
                attrs[name] = property(lambda self, _name=name: f"generated-{_name}")
            else:
                attrs[name] = _dummy_method

        harness = abc.ABCMeta(f"Generated{cls.__name__}Harness", (cls,), attrs)
        return harness()


def _flatten_observable(value):
    if isinstance(value, str):
        return [value]
    if isinstance(value, dict):
        values = []
        for item in value.values():
            values.extend(_flatten_observable(item))
        return values
    if isinstance(value, (list, tuple, set)):
        values = []
        for item in value:
            values.extend(_flatten_observable(item))
        return values
    return [str(value)]


@pytest.mark.parametrize("case", COMMON_AST_CASES, ids=[case["id"] for case in COMMON_AST_CASES])
def test_generated_common_ast_relation(case):
    source_cls = _load_class(case["source_module"], case["source_class"])
    owner_cls = _load_class(case["module_name"], case["class_name"])

    source = source_cls(**case["input_kwargs"])
    owner = _instance_for(owner_cls)
    result = getattr(owner, case["method_name"])(source)

    observed = "\n".join(str(item) for item in _flatten_observable(result))
    assert str(case["expected_value"]) in observed
