"""
Generated by tools/generate_pytest_from_properties.py.

These tests exercise composed interprocedural dataflow slices when a public
method can drive a source dataclass to an observable output dataclass.
"""

from __future__ import annotations

import abc
import importlib

import pytest


INTERPROCEDURAL_CASES = [

]


def _load_class(module_name, class_name):
    try:
        module = importlib.import_module(module_name)
    except ModuleNotFoundError as exc:
        pytest.skip(f"Cannot import {module_name}: {exc}")
    return getattr(module, class_name)


def _dummy_method(*args, **kwargs):
    return None


def _instance_for(cls):
    try:
        return cls()
    except TypeError:
        attrs = {}
        abstract_names = getattr(cls, "__abstractmethods__", set())
        for name in abstract_names:
            descriptor = getattr(cls, name, None)
            if isinstance(descriptor, property):
                attrs[name] = property(lambda self, _name=name: f"generated-{_name}")
            else:
                attrs[name] = _dummy_method

        harness = abc.ABCMeta(f"Generated{cls.__name__}Harness", (cls,), attrs)
        return harness()


def _flatten_observable(value):
    if value is None:
        return []
    if isinstance(value, str):
        return [value]
    if isinstance(value, dict):
        values = []
        for item in value.values():
            values.extend(_flatten_observable(item))
        return values
    if isinstance(value, (list, tuple, set)):
        values = []
        for item in value:
            values.extend(_flatten_observable(item))
        return values
    return [str(value)]


def _unwrap_pipeline_result(value):
    if hasattr(value, "value"):
        inner = getattr(value, "value")
        if inner is not None:
            return inner
    return value


@pytest.mark.parametrize("case", INTERPROCEDURAL_CASES, ids=[case["id"] for case in INTERPROCEDURAL_CASES])
def test_generated_interprocedural_observable_slice(case):
    source_cls = _load_class(case["source_module"], case["source_class"])
    owner_cls = _load_class(case["class_module"], case["class_name"])

    source = source_cls(**case["input_kwargs"])
    owner = _instance_for(owner_cls)
    result = _unwrap_pipeline_result(getattr(owner, case["method_name"])(source))

    actual = getattr(result, case["target_field"])
    observed = "\n".join(str(item) for item in _flatten_observable(actual))
    assert str(case["expected_value"]) in observed
