"""Emit a parametrized pytest suite from the Phase-1 metamorphic relations.

Each case applies a metamorphic transform to a source expression and asserts the
relation holds against the oracle -- a reference-free check (no recorded label).

Cases where the relation currently *fails* are emitted as ``xfail(strict=True)``
with a reason pointing at the finding, so the suite stays green, the bug is
documented inline, and a future fix flips the case to XPASS (a failure) to alert
us. The current corpus surfaces one such bug class via MR-DEADLET (see
``out/metamorphic_report.md`` and ``METAMORPHIC_FINDINGS.md``).
"""

from __future__ import annotations

import argparse
from pathlib import Path

from .compose import grow, size
from .generate_flip_tests import safe_id, to_source
from .groundtruth import build_ground_truth
from .metamorphic import MR_GENERATORS, MRInstance, check_instance, instances_for

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "generated_tests" / "type_checker_case_study"
TEST_PATH = "test_generated_metamorphic.py"

XFAIL_REASON = (
    "exposes a known inferLam substitution bug -- either a changed type under a "
    "semantics-preserving transform, or acceptance of an ill-typed program "
    "(see METAMORPHIC_FINDINGS.md)"
)


def _instance_size(inst: MRInstance) -> int:
    return size(inst.source) + size(inst.transformed)


def select_instances(
    sources, outcomes, *, per_mr_hold: int, per_mr_violation: int
) -> list[tuple[MRInstance, bool]]:
    """Return (instance, holds) pairs: holding and violating samples per MR.

    Both buckets are sampled per MR (smallest-first, for readability) so every
    bug-finding relation is represented in the suite rather than being crowded
    out by whichever MR happens to produce the smallest violations.
    """
    holding: dict[str, list[MRInstance]] = {mr: [] for mr in MR_GENERATORS}
    violating: dict[str, list[MRInstance]] = {mr: [] for mr in MR_GENERATORS}

    ranked_sources = sorted(sources, key=lambda e: (size(e), to_source(e)))
    for source in ranked_sources:
        for inst in instances_for(source, outcomes[source]):
            holds, _, _ = check_instance(inst)
            (holding if holds else violating)[inst.mr].append(inst)

    selected: list[tuple[MRInstance, bool]] = []
    for mr in sorted(holding):
        ranked = sorted(holding[mr], key=_instance_size)
        selected.extend((inst, True) for inst in ranked[:per_mr_hold])
    for mr in sorted(violating):
        ranked = sorted(violating[mr], key=_instance_size)
        selected.extend((inst, False) for inst in ranked[:per_mr_violation])
    return selected


def render_param(inst: MRInstance, holds: bool, seen_ids: set[str]) -> str:
    case_id = safe_id(inst.mr, to_source(inst.source), to_source(inst.transformed))
    base = case_id
    n = 1
    while case_id in seen_ids:
        n += 1
        case_id = f"{base}-{n}"
    seen_ids.add(case_id)

    body = "\n".join(
        [
            "        {",
            f"            'mr': {inst.mr!r},",
            f"            'relation': {inst.relation!r},",
            f"            'source': {to_source(inst.source)},",
            f"            'transformed': {to_source(inst.transformed)},",
            "        }",
        ]
    )
    if holds:
        return f"    pytest.param(\n{body},\n        id={case_id!r},\n    )"
    return (
        f"    pytest.param(\n{body},\n        id={case_id!r},\n"
        f"        marks=pytest.mark.xfail(strict=True, reason={XFAIL_REASON!r}),\n    )"
    )


def render_test_file(selected: list[tuple[MRInstance, bool]]) -> str:
    seen_ids: set[str] = set()
    params = ",\n".join(render_param(inst, holds, seen_ids) for inst, holds in selected)
    return f'''"""
Generated by type_checker_case_study/generate_metamorphic_tests.py.

Metamorphic-relation tests: each case applies a transform to a source
expression and asserts the relation holds against the oracle, with no recorded
"correct" answer. Cases marked xfail(strict) currently expose a checker bug; a
fix will flip them to XPASS and fail the suite, alerting us.

Run from the repo root:

    pytest generated_tests/type_checker_case_study/{TEST_PATH}
"""

from __future__ import annotations

import pytest

from type_checker_case_study.oracle.syntax import (
    App,
    EFalse,
    ETrue,
    If,
    Lam,
    Let,
    Lit,
    Var,
)
from type_checker_case_study.metamorphic import relation_holds
from type_checker_case_study.outcome import classify


CASES = [
{params}
]


@pytest.mark.parametrize("case", CASES)
def test_metamorphic_relation(case):
    src = classify(case["source"])
    dst = classify(case["transformed"])
    assert relation_holds(case["relation"], src, dst), (
        f"{{case['mr']}} ({{case['relation']}}) violated: "
        f"{{src.label}} -> {{dst.label}}"
    )
'''


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--max-size", type=int, default=9)
    parser.add_argument("--max-rounds", type=int, default=4)
    parser.add_argument("--cap-per-round", type=int, default=400)
    parser.add_argument("--per-mr-hold", type=int, default=12)
    parser.add_argument("--per-mr-violation", type=int, default=8)
    parser.add_argument("--output-dir", default=str(DEFAULT_OUTPUT))
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    composition = grow(
        max_size=args.max_size,
        max_rounds=args.max_rounds,
        cap_per_round=args.cap_per_round,
    )
    gt = build_ground_truth(composition)
    selected = select_instances(
        composition.expressions,
        gt.outcomes,
        per_mr_hold=args.per_mr_hold,
        per_mr_violation=args.per_mr_violation,
    )

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    test_path = out_dir / TEST_PATH
    test_path.write_text(render_test_file(selected), encoding="utf-8")

    holds = sum(1 for _, h in selected if h)
    xfails = sum(1 for _, h in selected if not h)
    print(f"emitted {len(selected)} cases ({holds} holding, {xfails} xfail) -> {test_path}")


if __name__ == "__main__":
    main()
