"""Promote discriminating mutations into a generated pytest suite.

Mirrors the repo's ``tools/generate_pytest_from_properties.py`` lane: select
validated cases, embed them as a literal in a generated test module, and let
pytest parametrize over them. Here the cases are the *discriminating mutations*
from the progressive composition loop -- single growth steps that flip the
validated outcome -- and the oracle under test is the ported type checker
itself.

Unlike the dataclass lane's loose ``_assert_observed`` oracle, every assertion
here is strict equality on the normalized outcome label (a principal-type shape
like ``(a -> a)`` or an error class like ``error:occurs-check``). That gives the
generated suite a strong oracle, which the repo README explicitly asks for.

The suite is regenerated deterministically from the same pipeline that writes
``out/flips.csv``; the CSV is the human-readable artifact, this is the
executable one.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from .compose import grow, size
from .groundtruth import Flip, build_ground_truth
from .oracle.syntax import App, EFalse, ETrue, Expr, If, Lam, Let, Lit, Var

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "generated_tests" / "type_checker_case_study"


def to_source(expr: Expr) -> str:
    """Render an expression as the Python constructor call that rebuilds it."""
    if isinstance(expr, Var):
        return f"Var({expr.name!r})"
    if isinstance(expr, Lam):
        return f"Lam({expr.var!r}, {to_source(expr.body)})"
    if isinstance(expr, App):
        return f"App({to_source(expr.fun)}, {to_source(expr.arg)})"
    if isinstance(expr, If):
        return (
            f"If({to_source(expr.cond)}, {to_source(expr.then_branch)}, "
            f"{to_source(expr.else_branch)})"
        )
    if isinstance(expr, Let):
        return f"Let({expr.name!r}, {to_source(expr.bound)}, {to_source(expr.body)})"
    if isinstance(expr, Lit):
        return f"Lit({expr.value!r})"
    if isinstance(expr, ETrue):
        return "ETrue()"
    if isinstance(expr, EFalse):
        return "EFalse()"
    raise TypeError(f"Unknown expression node: {expr!r}")


def safe_id(*parts: str) -> str:
    import re

    text = "-".join(parts)
    text = re.sub(r"[^A-Za-z0-9_.-]+", "-", text).strip("-")
    return text or "case"


def select_flips(flips: list[Flip], per_kind: int) -> list[Flip]:
    """Deterministically sample up to ``per_kind`` flips of each kind.

    Sorted by total size then text so minimal, easiest-to-read probes win, and
    so the suite is stable across runs.
    """
    by_kind: dict[str, list[Flip]] = {}
    for flip in flips:
        by_kind.setdefault(flip.kind, []).append(flip)
    selected: list[Flip] = []
    for kind in sorted(by_kind):
        ranked = sorted(
            by_kind[kind],
            key=lambda f: (size(f.parent) + size(f.child), to_source(f.parent), to_source(f.child)),
        )
        selected.extend(ranked[:per_kind])
    return selected


def render_cases(flips: list[Flip]) -> str:
    entries = []
    seen_ids: set[str] = set()
    for flip in flips:
        case_id = safe_id(flip.kind, to_source(flip.parent), to_source(flip.child))
        # keep ids unique even after sanitizing
        base = case_id
        n = 1
        while case_id in seen_ids:
            n += 1
            case_id = f"{base}-{n}"
        seen_ids.add(case_id)
        entries.append(
            "\n".join(
                [
                    "    {",
                    f"        'id': {case_id!r},",
                    f"        'kind': {flip.kind!r},",
                    f"        'parent': {to_source(flip.parent)},",
                    f"        'parent_outcome': {flip.parent_label!r},",
                    f"        'child': {to_source(flip.child)},",
                    f"        'child_outcome': {flip.child_label!r},",
                    "    }",
                ]
            )
        )
    return "[\n" + ",\n".join(entries) + "\n]"


def render_test_file(flips: list[Flip]) -> str:
    return f'''"""
Generated by type_checker_case_study/generate_flip_tests.py.

Each case is a discriminating mutation discovered by the progressive composition
loop: a single growth step that flips the type checker's validated outcome.
These pin the boundaries between well-typed and ill-typed composites (and
between distinct principal types) as regression tests.

Run from the repo root:

    pytest generated_tests/type_checker_case_study
"""

from __future__ import annotations

import pytest

from type_checker_case_study.oracle.syntax import (
    App,
    EFalse,
    ETrue,
    If,
    Lam,
    Let,
    Lit,
    Var,
)
from type_checker_case_study.outcome import classify


CASES = {render_cases(flips)}


def _outcome_label(expr):
    return classify(expr).label


def _is_error(label):
    return label.startswith("error:")


@pytest.mark.parametrize("case", CASES, ids=[case["id"] for case in CASES])
def test_composition_boundary(case):
    # The recorded validated outcomes must still hold exactly (strict oracle).
    assert _outcome_label(case["parent"]) == case["parent_outcome"]
    assert _outcome_label(case["child"]) == case["child_outcome"]

    # The mutation must genuinely change the outcome, in the recorded direction.
    assert case["parent_outcome"] != case["child_outcome"]
    parent_err = _is_error(case["parent_outcome"])
    child_err = _is_error(case["child_outcome"])
    if case["kind"] == "well->ill":
        assert not parent_err and child_err
    elif case["kind"] == "ill->well":
        assert parent_err and not child_err
    elif case["kind"] == "type-change":
        assert not parent_err and not child_err
    else:  # pragma: no cover - defensive
        pytest.fail(f"unknown flip kind: {{case['kind']!r}}")
'''


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--max-size", type=int, default=9)
    parser.add_argument("--max-rounds", type=int, default=4)
    parser.add_argument("--cap-per-round", type=int, default=400)
    parser.add_argument(
        "--per-kind",
        type=int,
        default=25,
        help="Maximum cases to emit per flip kind (well->ill, ill->well, type-change).",
    )
    parser.add_argument("--output-dir", default=str(DEFAULT_OUTPUT))
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    composition = grow(
        max_size=args.max_size,
        max_rounds=args.max_rounds,
        cap_per_round=args.cap_per_round,
    )
    gt = build_ground_truth(composition)
    flips = select_flips(gt.flips, args.per_kind)

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    test_path = out_dir / "test_generated_composition_boundaries.py"
    test_path.write_text(render_test_file(flips), encoding="utf-8")

    print(f"emitted {len(flips)} boundary cases -> {test_path}")


if __name__ == "__main__":
    main()
