"""
Generated by type_checker_case_study/generate_flip_tests.py.

Each case is a multi-step composition chain discovered by the progressive
mutation graph. These preserve the intermediate validated outcomes, so the
tests can pin a deeper "do this, then one more time, then again" progression
rather than only a single boundary flip.

Run from the repo root:

    pytest generated_tests/type_checker_case_study/test_generated_composition_chains.py
"""

from __future__ import annotations

import pytest

from type_checker_case_study.oracle.syntax import (
    App,
    EFalse,
    ETrue,
    If,
    Lam,
    Let,
    Lit,
    Var,
)
from type_checker_case_study.outcome import classify


CASES = [
    {
        'id': 'ill--well-chain-Lam-x-App-Var-x-Var-x--Lam-x-App-Lam-y-ETrue-Var-x--Lam-x-App-Lam-y-Lam-z-ETrue-Var-x--Lam-x-App-Lam-y-Lam-z-Lam-f-ETrue-Var-x',
        'kind': 'ill->well-chain',
        'expressions': [Lam('x', App(Var('x'), Var('x'))), Lam('x', App(Lam('y', ETrue()), Var('x'))), Lam('x', App(Lam('y', Lam('z', ETrue())), Var('x'))), Lam('x', App(Lam('y', Lam('z', Lam('f', ETrue()))), Var('x')))],
        'outcomes': ['error:occurs-check', '(a -> Bool)', '(a -> (b -> Bool))', '(a -> (b -> (c -> Bool)))'],
    },
    {
        'id': 'ill--well-chain-Lam-x-App-Var-x-Var-x--Lam-x-App-Lam-y-ETrue-Var-x--Lam-x-App-Lam-y-Lam-z-ETrue-Var-x--Lam-x-App-Lam-y-Lam-z-Lam-f-Var-f-Var-x',
        'kind': 'ill->well-chain',
        'expressions': [Lam('x', App(Var('x'), Var('x'))), Lam('x', App(Lam('y', ETrue()), Var('x'))), Lam('x', App(Lam('y', Lam('z', ETrue())), Var('x'))), Lam('x', App(Lam('y', Lam('z', Lam('f', Var('f')))), Var('x')))],
        'outcomes': ['error:occurs-check', '(a -> Bool)', '(a -> (b -> Bool))', '(a -> (b -> (c -> c)))'],
    },
    {
        'id': 'ill--well-chain-Lam-x-App-Var-x-Var-x--Lam-x-App-Lam-y-ETrue-Var-x--Lam-x-App-Lam-y-Lam-z-ETrue-Var-x--Lam-x-Lam-x-App-Lam-y-Lam-z-ETrue-Var-x',
        'kind': 'ill->well-chain',
        'expressions': [Lam('x', App(Var('x'), Var('x'))), Lam('x', App(Lam('y', ETrue()), Var('x'))), Lam('x', App(Lam('y', Lam('z', ETrue())), Var('x'))), Lam('x', Lam('x', App(Lam('y', Lam('z', ETrue())), Var('x'))))],
        'outcomes': ['error:occurs-check', '(a -> Bool)', '(a -> (b -> Bool))', '(a -> (b -> (c -> Bool)))'],
    },
    {
        'id': 'ill--well-chain-Lam-x-App-Var-x-Var-x--Lam-x-App-Lam-y-ETrue-Var-x--Lam-x-App-Lam-y-Lam-z-Var-z-Var-x--Lam-x-Lam-x-App-Lam-y-Lam-z-Var-z-Var-x',
        'kind': 'ill->well-chain',
        'expressions': [Lam('x', App(Var('x'), Var('x'))), Lam('x', App(Lam('y', ETrue()), Var('x'))), Lam('x', App(Lam('y', Lam('z', Var('z'))), Var('x'))), Lam('x', Lam('x', App(Lam('y', Lam('z', Var('z'))), Var('x'))))],
        'outcomes': ['error:occurs-check', '(a -> Bool)', '(a -> (b -> b))', '(a -> (b -> (c -> c)))'],
    },
    {
        'id': 'ill--well-chain-Lam-x-App-Var-x-Var-x--Lam-x-App-Lam-y-ETrue-Var-x--Lam-x-Lam-x-App-Lam-y-ETrue-Var-x--Lam-x-Lam-x-Lam-x-App-Lam-y-ETrue-Var-x',
        'kind': 'ill->well-chain',
        'expressions': [Lam('x', App(Var('x'), Var('x'))), Lam('x', App(Lam('y', ETrue()), Var('x'))), Lam('x', Lam('x', App(Lam('y', ETrue()), Var('x')))), Lam('x', Lam('x', Lam('x', App(Lam('y', ETrue()), Var('x')))))],
        'outcomes': ['error:occurs-check', '(a -> Bool)', '(a -> (b -> Bool))', '(a -> (b -> (c -> Bool)))'],
    },
    {
        'id': 'mixed-chain-Lam-x-Var-x--Lam-x-Lam-y-ETrue--Lam-x-Lam-y-App-Var-x-Var-x--Lam-x-Lam-y-App-Lam-z-Var-z-Var-x',
        'kind': 'mixed-chain',
        'expressions': [Lam('x', Var('x')), Lam('x', Lam('y', ETrue())), Lam('x', Lam('y', App(Var('x'), Var('x')))), Lam('x', Lam('y', App(Lam('z', Var('z')), Var('x'))))],
        'outcomes': ['(a -> a)', '(a -> (b -> Bool))', 'error:occurs-check', '(a -> (b -> a))'],
    },
    {
        'id': 'mixed-chain-Lam-x-Var-x--Lam-x-App-Var-x-Var-x--Lam-x-App-Lam-y-ETrue-Var-x--Lam-x-App-Lam-y-Lam-z-ETrue-Var-x',
        'kind': 'mixed-chain',
        'expressions': [Lam('x', Var('x')), Lam('x', App(Var('x'), Var('x'))), Lam('x', App(Lam('y', ETrue()), Var('x'))), Lam('x', App(Lam('y', Lam('z', ETrue())), Var('x')))],
        'outcomes': ['(a -> a)', 'error:occurs-check', '(a -> Bool)', '(a -> (b -> Bool))'],
    },
    {
        'id': 'mixed-chain-Lam-x-Var-x--Lam-x-App-Var-x-Var-x--Lam-x-App-Lam-y-ETrue-Var-x--Lam-x-App-Lam-y-Lam-z-Var-z-Var-x',
        'kind': 'mixed-chain',
        'expressions': [Lam('x', Var('x')), Lam('x', App(Var('x'), Var('x'))), Lam('x', App(Lam('y', ETrue()), Var('x'))), Lam('x', App(Lam('y', Lam('z', Var('z'))), Var('x')))],
        'outcomes': ['(a -> a)', 'error:occurs-check', '(a -> Bool)', '(a -> (b -> b))'],
    },
    {
        'id': 'mixed-chain-Lam-x-Var-x--Lam-x-App-Var-x-Var-x--Lam-x-App-Lam-y-ETrue-Var-x--Lam-x-Lam-x-App-Lam-y-ETrue-Var-x',
        'kind': 'mixed-chain',
        'expressions': [Lam('x', Var('x')), Lam('x', App(Var('x'), Var('x'))), Lam('x', App(Lam('y', ETrue()), Var('x'))), Lam('x', Lam('x', App(Lam('y', ETrue()), Var('x'))))],
        'outcomes': ['(a -> a)', 'error:occurs-check', '(a -> Bool)', '(a -> (b -> Bool))'],
    },
    {
        'id': 'mixed-chain-Lam-x-Var-x--Lam-x-Lam-y-ETrue--Lam-x-Lam-y-App-Var-x-Var-x--Lam-x-Lam-y-App-App-Var-y-ETrue-Var-x',
        'kind': 'mixed-chain',
        'expressions': [Lam('x', Var('x')), Lam('x', Lam('y', ETrue())), Lam('x', Lam('y', App(Var('x'), Var('x')))), Lam('x', Lam('y', App(App(Var('y'), ETrue()), Var('x'))))],
        'outcomes': ['(a -> a)', '(a -> (b -> Bool))', 'error:occurs-check', '(a -> ((Bool -> (a -> b)) -> b))'],
    },
    {
        'id': 'type-ladder-EFalse--Lam-x-EFalse--Lam-x-Lam-x-EFalse--Lam-x-Lam-x-Lam-x-EFalse',
        'kind': 'type-ladder',
        'expressions': [EFalse(), Lam('x', EFalse()), Lam('x', Lam('x', EFalse())), Lam('x', Lam('x', Lam('x', EFalse())))],
        'outcomes': ['Bool', '(a -> Bool)', '(a -> (b -> Bool))', '(a -> (b -> (c -> Bool)))'],
    },
    {
        'id': 'type-ladder-ETrue--Lam-x-ETrue--Lam-x-Lam-x-ETrue--Lam-x-Lam-x-Lam-x-ETrue',
        'kind': 'type-ladder',
        'expressions': [ETrue(), Lam('x', ETrue()), Lam('x', Lam('x', ETrue())), Lam('x', Lam('x', Lam('x', ETrue())))],
        'outcomes': ['Bool', '(a -> Bool)', '(a -> (b -> Bool))', '(a -> (b -> (c -> Bool)))'],
    },
    {
        'id': 'type-ladder-Lit-0--Lam-x-Lit-0--Lam-x-Lam-x-Lit-0--Lam-x-Lam-x-Lam-x-Lit-0',
        'kind': 'type-ladder',
        'expressions': [Lit(0), Lam('x', Lit(0)), Lam('x', Lam('x', Lit(0))), Lam('x', Lam('x', Lam('x', Lit(0))))],
        'outcomes': ['Int', '(a -> Int)', '(a -> (b -> Int))', '(a -> (b -> (c -> Int)))'],
    },
    {
        'id': 'type-ladder-Lit-0--Lam-x-Lit-0--Lam-x-Lam-x-Lit-0--Let-x-Lam-x-Lam-x-Lit-0-ETrue',
        'kind': 'type-ladder',
        'expressions': [Lit(0), Lam('x', Lit(0)), Lam('x', Lam('x', Lit(0))), Let('x', Lam('x', Lam('x', Lit(0))), ETrue())],
        'outcomes': ['Int', '(a -> Int)', '(a -> (b -> Int))', 'Bool'],
    },
    {
        'id': 'type-ladder-Lit-0--Lam-x-Lit-0--Let-x-Lam-x-Lit-0-ETrue--Lam-x-Let-x-Lam-x-Lit-0-ETrue',
        'kind': 'type-ladder',
        'expressions': [Lit(0), Lam('x', Lit(0)), Let('x', Lam('x', Lit(0)), ETrue()), Lam('x', Let('x', Lam('x', Lit(0)), ETrue()))],
        'outcomes': ['Int', '(a -> Int)', 'Bool', '(a -> Bool)'],
    },
    {
        'id': 'well--ill-chain-Lit-0--Lam-x-Lit-0--Let-x-Lam-x-Lit-0-ETrue--Let-x-Lam-x-Lit-0-If-Var-x-ETrue-EFalse',
        'kind': 'well->ill-chain',
        'expressions': [Lit(0), Lam('x', Lit(0)), Let('x', Lam('x', Lit(0)), ETrue()), Let('x', Lam('x', Lit(0)), If(Var('x'), ETrue(), EFalse()))],
        'outcomes': ['Int', '(a -> Int)', 'Bool', 'error:non-bool-condition'],
    },
    {
        'id': 'well--ill-chain-Lit-0--Let-x-Lit-0-ETrue--Lam-x-Let-x-Lit-0-ETrue--Lam-x-Let-x-App-Var-x-Var-x-ETrue',
        'kind': 'well->ill-chain',
        'expressions': [Lit(0), Let('x', Lit(0), ETrue()), Lam('x', Let('x', Lit(0), ETrue())), Lam('x', Let('x', App(Var('x'), Var('x')), ETrue()))],
        'outcomes': ['Int', 'Bool', '(a -> Bool)', 'error:occurs-check'],
    },
    {
        'id': 'well--ill-chain-Lit-0--Let-x-Lit-0-ETrue--Lam-x-Let-x-Lit-0-ETrue--Lam-x-Let-x-Lit-0-App-Var-x-ETrue',
        'kind': 'well->ill-chain',
        'expressions': [Lit(0), Let('x', Lit(0), ETrue()), Lam('x', Let('x', Lit(0), ETrue())), Lam('x', Let('x', Lit(0), App(Var('x'), ETrue())))],
        'outcomes': ['Int', 'Bool', '(a -> Bool)', 'error:application-mismatch'],
    },
    {
        'id': 'well--ill-chain-Lit-0--Let-x-Lit-0-ETrue--Lam-x-Let-x-Lit-0-ETrue--Lam-x-Let-x-Lit-0-App-Var-x-Var-x',
        'kind': 'well->ill-chain',
        'expressions': [Lit(0), Let('x', Lit(0), ETrue()), Lam('x', Let('x', Lit(0), ETrue())), Lam('x', Let('x', Lit(0), App(Var('x'), Var('x'))))],
        'outcomes': ['Int', 'Bool', '(a -> Bool)', 'error:application-mismatch'],
    },
    {
        'id': 'well--ill-chain-Lit-0--Let-x-Lit-0-ETrue--Let-x-Lit-0-Lam-y-ETrue--Let-x-Lit-0-Lam-y-App-Var-x-ETrue',
        'kind': 'well->ill-chain',
        'expressions': [Lit(0), Let('x', Lit(0), ETrue()), Let('x', Lit(0), Lam('y', ETrue())), Let('x', Lit(0), Lam('y', App(Var('x'), ETrue())))],
        'outcomes': ['Int', 'Bool', '(a -> Bool)', 'error:application-mismatch'],
    }
]


def _outcome_label(expr):
    return classify(expr).label


@pytest.mark.parametrize("case", CASES, ids=[case["id"] for case in CASES])
def test_composition_chain(case):
    expressions = case["expressions"]
    recorded = case["outcomes"]
    observed = [_outcome_label(expr) for expr in expressions]
    assert observed == recorded
    assert len(observed) >= 4
    assert len(set(observed)) == len(observed)
